import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/main/navbar";
import Sidebar from "@/components/main/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Marketplace",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          bg-neutral-200 min-h-dvh
        `}
      >
        <Navbar />
        <div className="md:flex h-full">
          <Sidebar />
          <div className="w-full md:max-w-xs"></div>
          <main className="md:flex-1 p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
